### ISSUE TITLE
Will this work with firmware v2.77 fan hack?

### ISSUE THREAD

**Issue by NikuZai** [alex3025/ilo-fans-controller#1] opened 2022-07-02 18:53 UTC
Hi,

will this HP-ILO-Fan-Control work also with 2.77 fan hack "ilo4_unlock (Silence of the Fans)" (https://github.com/kendallgoto/ilo4_unlock)? If not, are there any plans to bring support for it?

Thanks in advance!

**Comment by alex3025** [comment] 2022-07-03 15:17
Yes, it should work without any modifications!
The ssh commands used to manage the speeds are the same.

**Comment by mboyd1** [comment] 2022-07-04 20:43
I'm running the 2.77 but I can't seem to get the fan ssh commands to work nor this.   I refresh the php and it goes back to 94% fan speed every time - I lower it and apply, and get a white screen of nothing.  when I refresh again it says 94%. 
fans still deafeningly loud.  not sure where the problem is yet

**Comment by alex3025** [comment] 2022-07-04 20:58
> I'm running the modified 2.77 from @kendallgoto  but I can't seem to get the fan ssh commands to work nor this.   I refresh the php and it goes back to 94% fan speed every time - I lower it and apply, and get a white screen of nothing.  when I refresh again it says 94%. 
> fans still deafeningly loud.  not sure where the problem is yet.  hp dl360p servers

Are you able to set the speeds from iLO ssh?

If yes, which commands do you type?

**Comment by mboyd1** [comment] 2022-07-04 21:42
after further playing with this modified ilo, I see that I need to look at each individual sensor with ex. 'fan info a'  and 'fan info g' and find which sensor(s) are causing the fans to spin up high, and modify the hi/lo values for each sensor

**Comment by alex3025** [comment] 2022-07-05 07:27
So you can't use `fan p X min Y` and `fan p X max Y` to set the speeds?

**Comment by alex3025** [comment] 2022-08-04 19:53
Yesterday I've installed myself the 2.77 fan hack update, and I haven't encountered any issues so I think I can close this for now.

**Closed by alex3025** 2022-08-04 19:53 UTC
